version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Change if your package.json is in a subdirectory
    schedule:
      interval: "weekly" # Can be daily, weekly, or monthly

  - package-ecosystem: "github-actions"
    directory: "/" # For workflows in .github/workflows
    schedule:
      interval: "weekly"